services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # For microservices
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  authservice:
    build:
      context: .
      dockerfile: ./Dockerfile.authservice
    container_name: authservice
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: uat
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest

  userservice:
    build:
      context: .
      dockerfile: ./Dockerfile.userservice
    container_name: userservice
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: uat
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest

  chatservice:
    build:
      context: .
      dockerfile: ./Dockerfile.chatservice
    container_name: chatservice
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: uat
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest

volumes:
  redis_data:
